<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductsSeeder extends Seeder
{
    /**
     * Jalankan database seeds.
     */
    public function run(): void
    {
        // Menghapus data lama di tabel jika perlu, untuk menghindari duplikat saat seeder dijalankan ulang
        // DB::table('products')->truncate();

        DB::table('products')->insert([
            // === PRODUK SAYUR (id_kategori = 1) ===
            [
                'nama' => 'Arugula',
                'id_kategori' => 1,
                'harga' => 18000,
                'stok' => 70,
                'gambar' => 'Produk_Sayur/Arugula.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Bayam',
                'id_kategori' => 1,
                'harga' => 10000,
                'stok' => 150,
                'gambar' => 'Produk_Sayur/Bayam.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Butterhead',
                'id_kategori' => 1,
                'harga' => 15000,
                'stok' => 80,
                'gambar' => 'Produk_Sayur/Butterhead.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Cabai Keriting',
                'id_kategori' => 1,
                'harga' => 25000,
                'stok' => 120,
                'gambar' => 'Produk_Sayur/Cabaikeriting.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Dakota',
                'id_kategori' => 1,
                'harga' => 16000,
                'stok' => 90,
                'gambar' => 'Produk_Sayur/Dakota.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Kale',
                'id_kategori' => 1,
                'harga' => 22000,
                'stok' => 60,
                'gambar' => 'Produk_Sayur/Kale.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Kemangi',
                'id_kategori' => 1,
                'harga' => 5000,
                'stok' => 200,
                'gambar' => 'Produk_Sayur/Kemangi.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Kubis',
                'id_kategori' => 1,
                'harga' => 12000,
                'stok' => 100,
                'gambar' => 'Produk_Sayur/Kubis.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Lobak Putih',
                'id_kategori' => 1,
                'harga' => 13000,
                'stok' => 85,
                'gambar' => 'Produk_Sayur/LobakPutih.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Mizuna',
                'id_kategori' => 1,
                'harga' => 17000,
                'stok' => 75,
                'gambar' => 'Produk_Sayur/Mizuna.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Mustard',
                'id_kategori' => 1,
                'harga' => 14000,
                'stok' => 95,
                'gambar' => 'Produk_Sayur/Mustard.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Pakcoy',
                'id_kategori' => 1,
                'harga' => 11000,
                'stok' => 130,
                'gambar' => 'Produk_Sayur/Pakcoy.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Pakoi',
                'id_kategori' => 1,
                'harga' => 11500,
                'stok' => 125,
                'gambar' => 'Produk_Sayur/Pakoi.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Paprika',
                'id_kategori' => 1,
                'harga' => 30000,
                'stok' => 50,
                'gambar' => 'Produk_Sayur/Paprika.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Parsley',
                'id_kategori' => 1,
                'harga' => 8000,
                'stok' => 110,
                'gambar' => 'Produk_Sayur/Parsley.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Red Pak Choy',
                'id_kategori' => 1,
                'harga' => 13000,
                'stok' => 100,
                'gambar' => 'Produk_Sayur/RedPakChoy.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Romaine',
                'id_kategori' => 1,
                'harga' => 16000,
                'stok' => 90,
                'gambar' => 'Produk_Sayur/Romaine.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Sawi',
                'id_kategori' => 1,
                'harga' => 9000,
                'stok' => 160,
                'gambar' => 'Produk_Sayur/Sawi.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Selada Hijau',
                'id_kategori' => 1,
                'harga' => 10000,
                'stok' => 140,
                'gambar' => 'Produk_Sayur/SeladaHijau.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Seledri',
                'id_kategori' => 1,
                'harga' => 7000,
                'stok' => 180,
                'gambar' => 'Produk_Sayur/Seledri.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Tatsoi',
                'id_kategori' => 1,
                'harga' => 17500,
                'stok' => 65,
                'gambar' => 'Produk_Sayur/Tatsoi.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Wortel',
                'id_kategori' => 1,
                'harga' => 14000,
                'stok' => 150,
                'gambar' => 'Produk_Sayur/Wortel.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // === PRODUK BUAH (id_kategori = 2) ===
            [
                'nama' => 'Anggur',
                'id_kategori' => 2,
                'harga' => 45000,
                'stok' => 80,
                'gambar' => 'Produk_Buah/Anggur.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Apel',
                'id_kategori' => 2,
                'harga' => 35000,
                'stok' => 100,
                'gambar' => 'Produk_Buah/Apel.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Apel Hijau',
                'id_kategori' => 2,
                'harga' => 32000,
                'stok' => 90,
                'gambar' => 'Produk_Buah/ApelHijau.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Aprikot',
                'id_kategori' => 2,
                'harga' => 55000,
                'stok' => 50,
                'gambar' => 'Produk_Buah/Aprikot.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Atemoya',
                'id_kategori' => 2,
                'harga' => 60000,
                'stok' => 40,
                'gambar' => 'Produk_Buah/Atemoya.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Belimbing',
                'id_kategori' => 2,
                'harga' => 20000,
                'stok' => 120,
                'gambar' => 'Produk_Buah/Belimbing.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Blackberry',
                'id_kategori' => 2,
                'harga' => 65000,
                'stok' => 60,
                'gambar' => 'Produk_Buah/Blackberry.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Blewah',
                'id_kategori' => 2,
                'harga' => 15000,
                'stok' => 70,
                'gambar' => 'Produk_Buah/Blewah.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Blueberry',
                'id_kategori' => 2,
                'harga' => 70000,
                'stok' => 55,
                'gambar' => 'Produk_Buah/Blueberry.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Buah Naga',
                'id_kategori' => 2,
                'harga' => 28000,
                'stok' => 95,
                'gambar' => 'Produk_Buah/BuahNaga.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Ceri',
                'id_kategori' => 2,
                'harga' => 80000,
                'stok' => 45,
                'gambar' => 'Produk_Buah/Ceri.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Delima',
                'id_kategori' => 2,
                'harga' => 40000,
                'stok' => 65,
                'gambar' => 'Produk_Buah/Delima.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Fig',
                'id_kategori' => 2,
                'harga' => 75000,
                'stok' => 35,
                'gambar' => 'Produk_Buah/Fig.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Gooseberry',
                'id_kategori' => 2,
                'harga' => 68000,
                'stok' => 40,
                'gambar' => 'Produk_Buah/Goosberry.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Guava',
                'id_kategori' => 2,
                'harga' => 22000,
                'stok' => 110,
                'gambar' => 'Produk_Buah/Guava.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Jeruk',
                'id_kategori' => 2,
                'harga' => 25000,
                'stok' => 150,
                'gambar' => 'Produk_Buah/Jeruk.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Kismis',
                'id_kategori' => 2,
                'harga' => 30000,
                'stok' => 200,
                'gambar' => 'Produk_Buah/Kismis.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Kiwi',
                'id_kategori' => 2,
                'harga' => 48000,
                'stok' => 70,
                'gambar' => 'Produk_Buah/Kiwi.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Lemon',
                'id_kategori' => 2,
                'harga' => 23000,
                'stok' => 90,
                'gambar' => 'Produk_Buah/Lemon.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Mangga',
                'id_kategori' => 2,
                'harga' => 30000,
                'stok' => 130,
                'gambar' => 'Produk_Buah/Mangga.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Mangga Hitam',
                'id_kategori' => 2,
                'harga' => 85000,
                'stok' => 30,
                'gambar' => 'Produk_Buah/ManggaHitam.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Markisa',
                'id_kategori' => 2,
                'harga' => 27000,
                'stok' => 85,
                'gambar' => 'Produk_Buah/Markisa.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Melon',
                'id_kategori' => 2,
                'harga' => 20000,
                'stok' => 60,
                'gambar' => 'Produk_Buah/Melon.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Nanas',
                'id_kategori' => 2,
                'harga' => 18000,
                'stok' => 75,
                'gambar' => 'Produk_Buah/Nanas.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Pir',
                'id_kategori' => 2,
                'harga' => 34000,
                'stok' => 90,
                'gambar' => 'Produk_Buah/Pir.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Pokat',
                'id_kategori' => 2,
                'harga' => 29000,
                'stok' => 100,
                'gambar' => 'Produk_Buah/Pokat.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Raspberry',
                'id_kategori' => 2,
                'harga' => 72000,
                'stok' => 50,
                'gambar' => 'Produk_Buah/Raspberry.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Strawberry',
                'id_kategori' => 2,
                'harga' => 40000,
                'stok' => 110,
                'gambar' => 'Produk_Buah/Strawberry.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Zaitun',
                'id_kategori' => 2,
                'harga' => 90000,
                'stok' => 25,
                'gambar' => 'Produk_Buah/Zaitun.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
